funker

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -4,6 +4,8 @@ on:
  push:
   branches:
    - main
+
+
 jobs:
   deploy:
     name: deploy to Self-hosted Runner
@@ -13,27 +15,26 @@ jobs:
      - name: Checkout code
       uses: actions/checkout@v3
 
-      -name: Pull latest changes
-      run: git pull --no-edit origin main
+      - name: Pull latest changes
+        run: git pull --no-edit origin main
 
-      -name: set up Node.ejs
-      uses: actions/setup-node@v3
-      with:
-       node-version: "18"
+      - name: set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: "18"
 
-       -name: install dependencies
-       working-directory: ./
-       run: npm install
+      - name: install dependencies
+        working-directory: ./
+        run: npm install
 
-       -name: reload with PM2
-       run: |
-        echo "reloading server"
-        pm2 reload server --update env
+      - name: reload with PM2
+        run: |
+          echo "reloading server"
+          pm2 reload server --update env
 
-      -name: Verify PM2 status
-      run: |
-       pm2  status 
-       if pm2 list | grep -qE "errored|stopped"; then
-          echo "one or more processes have errored or stopped" 
-          exit 1
-       fi
+      - name: Verify PM2 status
+        run: |
+          if pm2 list | grep -qE "errored|stopped"; then
+              echo "one or more processes have errored or stopped" 
+              exit 1
+          fi
